### ISSUE TITLE
谢谢你的工作，跑运行的时候发现文件缺失

### ISSUE THREAD

**Issue by riverind** [LibertFan/AI_Hospital#1]
目前运行run.sh脚本，提示error，文件缺失
FileNotFoundError: [Errno 2] No such file or directory: './data/iiyi/patients.json'
查看文件，data下也确实没有该文件夹iiyi。
想确认下，是data/patients.json这个文件嘛，谢谢您

**Comment by LibertFan** [comment]
下载一下https://github.com/LibertFan/AI_Hospital/blob/main/src/data/patients.json这个数据，放到文件夹下面就可以了

**Comment by LibertFan** [comment]
./data/iiyi/patients.json 就是这个 https://github.com/LibertFan/AI_Hospital/blob/main/src/data/patients.json 哈，你可以得调整一下文件的相对路径，在src下面来执行

**Comment by riverind** [comment]
好的，谢谢您

祝好
















在 2024-05-27 15:01:57，"Zhihao Fan" ***@***.***> 写道：

./data/iiyi/patients.json 就是这个 https://github.com/LibertFan/AI_Hospital/blob/main/src/data/patients.json 哈，你可以得调整一下文件的相对路径，在src下面来执行
