### ISSUE TITLE
Questions about the metrics in Table 3

### ISSUE THREAD

**Issue by HXX97** [LibertFan/AI_Hospital#2]
Thank you for your nice work, it is very inspiring.

I would like to learn more about the normalized score in Table 3. Some lowest scores are normlized to the highest, while some highest scores are normalized to the lowest. And some same scores are normalized to different scores. Could you explain how the metrics are normalized in detail? It really confuses me. Thanks a lot!

![cac461a9f0b83f35d8f13535f088fa2](https://github.com/LibertFan/AI_Hospital/assets/23658059/198795bf-4669-441f-842d-e653ee89265d)

**Comment by LibertFan** [comment]
The scores in parentheses is the standard deviation calculated through bootstrapping.

**Comment by HXX97** [comment]
> The scores in parentheses is the standard deviation calculated through bootstrapping.

Thank you for your reply. The chief physician gives a score out of ['A','B','C','D'], which is mapped to [4,3,2,1]. Then the mean value and deviation is calculated through bootstrapping. Finally the mean value is normalized to 0-100 by scaling, where s = (x-1)*100/(4-1), so does the deviation score. Did I get that right?

**Comment by LibertFan** [comment]
> > The scores in parentheses is the standard deviation calculated through bootstrapping.
> 
> Thank you for your reply. The chief physician gives a score out of ['A','B','C','D'], which is mapped to [4,3,2,1]. Then the mean value and deviation is calculated through bootstrapping. Finally the mean value is normalized to 0-100 by scaling, where s = (x-1)*100/(4-1), so does the deviation score. Did I get that right?

That is correct.

**Comment by LibertFan** [comment]
> > The scores in parentheses is the standard deviation calculated through bootstrapping.
> 
> Thank you for your reply. The chief physician gives a score out of ['A','B','C','D'], which is mapped to [4,3,2,1]. Then the mean value and deviation is calculated through bootstrapping. Finally the mean value is normalized to 0-100 by scaling, where s = (x-1)*100/(4-1), so does the deviation score. Did I get that right?

Yes

**Comment by HXX97** [comment]
> > > The scores in parentheses is the standard deviation calculated through bootstrapping.
> > 
> > 
> > Thank you for your reply. The chief physician gives a score out of ['A','B','C','D'], which is mapped to [4,3,2,1]. Then the mean value and deviation is calculated through bootstrapping. Finally the mean value is normalized to 0-100 by scaling, where s = (x-1)*100/(4-1), so does the deviation score. Did I get that right?
> 
> Yes

Got it. Thanks!
