### ISSUE TITLE
数据集中raw_medical_record与medical_record的区别

### ISSUE THREAD

**Issue by FutureForMe** [LibertFan/AI_Hospital#3]
您好，我看到数据集中raw_medical_record与medical_record之间除了格式上的一些区别，鉴别诊断、诊治经过等字段的表述上也存在区别，因此想请教一下是如何处理raw_medical_record得到的medical_record?

<img width="1902" alt="image" src="https://github.com/user-attachments/assets/ebeb363b-206f-410b-adfc-244f18cdd344">

**Comment by LibertFan** [comment]
medical_record用GPT来整理了行文表达，因而整体的表达结构会好一点，例如把不同的要点一一分开罗列，主要针对的是查体和辅助检查的部分。在后续输入LLM里面去的时候，更方便LLM的理解，也方便人的阅读和理解，以及后续的分析实验计算数值。

**Comment by FutureForMe** [comment]
OK, 了解，感谢解答
