### ISSUE TITLE
Question about the file "patients.json"

### ISSUE THREAD

**Issue by Clifx9908** [LibertFan/AI_Hospital#4]
Thank you for your excellent work. Not only in the overall paper, but in the open-source project.   
  I have some questions about the "patient.json" file and would like to ask for your guidance, thank you so much!
  About all, I don't know how to get the reformed text medical record, whether it was generated by GPT-4 or written by doctor?  Besides, if it is convenient for you, I would like to know the way you obtain the "profile" in the data. It seems to be applying a prompt to generate.

![patients_json](https://github.com/user-attachments/assets/5cf7c55e-800b-4181-aafb-452375fdcd50)

**Comment by LibertFan** [comment]
1. Generated by GPT-4.
2. Profile is generated by GPT-4 based on "一般资料"， “主诉”，"现病史", "既往史"

**Comment by Clifx9908** [comment]
I get it. Thank you so much!
