### ISSUE TITLE
Question about foregt() in Doctor 

### ISSUE THREAD

**Issue by 1940653868** [LibertFan/AI_Hospital#5]
感谢作者的开源，我在阅读代码中有一个疑问，烦请解答
    def forget(self, patient_id=None):
        def default_value_factory():
            return [("system", self.system_message)]
        if patient_id is None:
            self.memories.pop(patient_id)
        else:
            self.memories = defaultdict(default_value_factory) 
请问在Doctor类中forget方法为什么在id为None的时候去操作memories(patient_id)？

**Comment by LibertFan** [comment]
感谢您的检查，是bug，已经修复了
